name: Trigger Airflow DAG

on:
  push:
    branches:
      - dev

jobs:
  trigger_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Airflow DAG
      run: |
        python3 /home/runner/work/fraude-detection/app/action.py