name: Trigger Airflow DAG

on:
  push:
    branches:
      - dev

jobs:
  trigger_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Airflow DAG
      working-directory: ./fraude-detection  # Specify the correct path
      run: |
        python3 action.py
