name: Trigger Airflow DAG

on:
  push:
    branches:
      - main

jobs:
  trigger_airflow_dag:
    runs-on: ubuntu-latest

    steps:
    - name: Install Ngrok
      run: |
        echo "Installing Ngrok..."
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        sudo mv ngrok /usr/local/bin/ngrok

    - name: Start Ngrok Tunnel
      run: |
        echo "Starting Ngrok tunnel..."
        ngrok http 8080

    - name: Display Ngrok Debug Info
      run: |
        echo "Displaying Ngrok debug info..."
        curl http://localhost:4040/api/tunnels
